package com.pritanjalis.airbnb.domain;


import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

import javax.persistence.*;
import java.io.Serializable;

@Entity
@ApiModel(description = "Details of Airbnb entity")
@Table(name = "AIRBNB_PROPERTY")
public class AirbnbProperty implements Serializable {

	private static final long serialVersionUID = 1L;

	@Id
    @GeneratedValue(strategy = GenerationType.AUTO)
    @Column(name = "BNB_ID")
    @ApiModelProperty(notes = "Autogenerated ID for Airbnb Property.")
    private Long bnbId;

    @Column(name = "PROPERTY_ID")
    @ApiModelProperty(notes = "Property ID of Airbnb Property")
    private String propertyId;

    @ApiModelProperty(notes = "Location of the property. This can not be blank.")
    private String location;

    @Column(name = "BEDROOMS")
    @ApiModelProperty(notes = "Number of bedroom in the property. This can not be blank.")
    private Integer numOfBedroom;

    @Column(name = "BATHROOMS")
    @ApiModelProperty(notes = "Number of bathroom in the property. This can not be blank.")
    private Integer numOfBathroom;

    @Column(name = "GUESTS")
    @ApiModelProperty(notes = "Number of guests for accommodation. This can not be blank.")
    private Integer guests;

    @Enumerated(EnumType.STRING)
    @Column(name = "TYPE")
    @ApiModelProperty(notes = "Type of BNB. This can not be blank.")
    private AirbnbPropertyType type;

    @Column(name = "RATE")
    @ApiModelProperty(notes = "Rate of the accommodation per day. This should be a positive number.")
    private float rate;


    public AirbnbProperty() {

    }

    public AirbnbProperty(final String propertyId, final String location, final Integer numOfBedroom, final Integer numOfBathroom, final Integer guests, final AirbnbPropertyType type, final float rate) {
        super();
        this.propertyId = propertyId;
        this.location = location;
        this.numOfBedroom = numOfBedroom;
        this.numOfBathroom = numOfBathroom;
        this.guests = guests;
        this.type = type;
        this.rate = rate;
    }

    

    public Long getBnbId() {
		return bnbId;
	}

	public void setBnbId(final Long bnbId) {
		this.bnbId = bnbId;
	}

	public String getLocation() {
		return location;
	}

	public void setLocation(final String location) {
		this.location = location;
	}

    public String getPropertyId() {
		return propertyId;
	}

	public void setPropertyId(final String propertyId) {
		this.propertyId = propertyId;
	}


	public Integer getNumOfBedroom() {
		return numOfBedroom;
	}

	public void setNumOfBedroom(final Integer numOfBedroom) {
		this.numOfBedroom = numOfBedroom;
	}

	public Integer getNumOfBathroom() {
		return numOfBathroom;
	}

	public void setNumOfBathroom(final Integer numOfBathroom) {
		this.numOfBathroom = numOfBathroom;
	}

	public Integer getGuests() {
		return guests;
	}

	public void setGuests(final Integer guests) {
		this.guests = guests;
	}

	public AirbnbPropertyType getType() {
		return type;
	}

	public void setType(final AirbnbPropertyType type) {
		this.type = type;
	}

	public float getRate() {
		return rate;
	}

	public void setRate(final float rate) {
		this.rate = rate;
	}


}
