INSERT INTO AIRBNB_PROPERTY (BNB_ID, PROPERTY_ID, LOCATION, BEDROOMS,  BATHROOMS, GUESTS , TYPE, RATE) VALUES (1, 'IRL-WH-ATH-1', 'Westmeath', 3, 2, 6, 'FLAT', 100.00);
INSERT INTO AIRBNB_PROPERTY (BNB_ID, PROPERTY_ID, LOCATION, BEDROOMS,  BATHROOMS, GUESTS , TYPE, RATE) VALUES (2, 'IRL-WH-ATH-2', 'Westmeath', 3, 2, 6, 'HOUSE', 200.00);
INSERT INTO AIRBNB_PROPERTY (BNB_ID, PROPERTY_ID, LOCATION, BEDROOMS,  BATHROOMS, GUESTS , TYPE, RATE) VALUES (3, 'IRL-DUB-CITY-1', 'Dublin', 3, 2, 6, 'FLAT', 100.00);
INSERT INTO AIRBNB_PROPERTY (BNB_ID, PROPERTY_ID, LOCATION, BEDROOMS,  BATHROOMS, GUESTS , TYPE, RATE) VALUES (4, 'IRL-DUB-CITY-2', 'Dublin', 3, 2, 6, 'HOUSE', 300.00);
INSERT INTO AIRBNB_PROPERTY (BNB_ID, PROPERTY_ID, LOCATION, BEDROOMS,  BATHROOMS, GUESTS , TYPE, RATE) VALUES (5, 'IRL-DUB-CITY-3', 'Dublin', 3, 2, 6, 'VILLA', 1000.00);
